# Generated by Django 4.2.2 on 2023-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('created_time',)},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
